version: '3.8'

services:
  web:
    build: .
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:power2024@db:3306/speedymart
      - SQLALCHEMY_TRACK_MODIFICATIONS=False
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: power2024
      MYSQL_DATABASE: speedymart
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
