version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    networks:
      - my_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: power2024
      MYSQL_DATABASE: speedymart
    ports:
      - "3306:3306"
    networks:
      - my_network

networks:
  my_network:
