name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: power2024
          MYSQL_DATABASE: intrestDB
          MYSQL_USER: root
          MYSQL_PASSWORD: power2024
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h db --silent; do
          echo 'Waiting for MySQL...'
          sleep 3
        done

    - name: Run tests
      env:
        DATABASE_URL: mysql+pymysql://user:power2024@db:3306/speedymart
      run: |
        pytest

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/speedymart:latest

    - name: Deploy to server
      run: |
        ssh user@your-server 'docker pull ${{ secrets.DOCKER_USERNAME }}/speedymart:latest && docker-compose up -d'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
